# build stage
FROM golang:1.17.0-alpine3.14 AS build-env

RUN apk update && apk upgrade && \
    apk add --no-cache bash git

ARG RELEASE=unknown
ARG COMMIT=unknown
ARG BUILD_TIME=unknown

ENV PROJECT "github.com/liskl/batrium-udp2http-bridge/client"
ENV RELEASE ${RELEASE}
ENV COMMIT ${COMMIT}
ENV BUILD_TIME ${BUILD_TIME}

COPY ./client/client.go /go/src/github.com/liskl/batrium-udp2http-bridge/client/client.go
COPY ./batrium /go/src/github.com/liskl/batrium-udp2http-bridge/batrium

WORKDIR /go/src/github.com/liskl/batrium-udp2http-bridge/client

RUN go get github.com/liskl/batrium-udp2http-bridge/client \
    && go build \
  		-ldflags "-s -w \
      -X ${PROJECT}/main.Release=${RELEASE} \
  		-X ${PROJECT}/main.Commit=${COMMIT} \
      -X ${PROJECT}/main.BuildTime=${BUILD_TIME}" \
  		-o client ;

RUN find /go/src -type d

# final stage
FROM alpine:3.15
WORKDIR /app
COPY --from=build-env /go/src/github.com/liskl/batrium-udp2http-bridge/client /app/
CMD ["/app/client"]
